# ND Array의 선형 대수

In [2]:
from mxnet import nd

### 1. Scalar

In [3]:
# nd arrray scalar 인스턴스 생성
x = nd.array([3.0])
y = nd.array([2.0])

In [4]:
print('x =', x)
print('y =', y)
print('x + y =', x + y)
print('x * y =', x * y)
print('x / y =', x / y)
print('x ** y =', x ** y)

x = 
[ 3.]
<NDArray 1 @cpu(0)>
y = 
[ 2.]
<NDArray 1 @cpu(0)>
x + y = 
[ 5.]
<NDArray 1 @cpu(0)>
x * y = 
[ 6.]
<NDArray 1 @cpu(0)>
x / y = 
[ 1.5]
<NDArray 1 @cpu(0)>
x ** y = 
[ 9.]
<NDArray 1 @cpu(0)>


In [5]:
# NDArray Scalar 값을 Python 기본 float으로 바꾸고 싶으면 asscalar 이용
print(x.asscalar())
print(x.shape)
z = nd.array([1, 1, 1])
print('z =', z)
print(z.shape)
print(z.asscalar())
# scalar가 아니면 asscalar 사용 불가능.(Vector 이상의 차원은 불가능)

3.0
(1,)
z = 
[ 1.  1.  1.]
<NDArray 3 @cpu(0)>
(3,)


ValueError: The current array is not a scalar

### 2. Vector

In [6]:
u = nd.arange(4)
print('u =', u)

u = 
[ 0.  1.  2.  3.]
<NDArray 4 @cpu(0)>


In [7]:
u[3]


[ 3.]
<NDArray 1 @cpu(0)>

### 3. Length, Dimensionality, Shape

In [8]:
len(u)

4

In [9]:
u.shape

(4,)

In [10]:
a = 2
x = nd.array([1, 2, 3])
y = nd.array([10, 20, 30])
print(a * x)
print(a * x + y)


[ 2.  4.  6.]
<NDArray 3 @cpu(0)>

[ 12.  24.  36.]
<NDArray 3 @cpu(0)>


### 4. Matrices

In [11]:
A = nd.zeros((5, 4))
A


[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
<NDArray 5x4 @cpu(0)>

In [14]:
x = nd.arange(20)
A = x.reshape((5, 4))
print(x, x.shape)
print(A, A.shape)


[  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.
  15.  16.  17.  18.  19.]
<NDArray 20 @cpu(0)> (20,)

[[  0.   1.   2.   3.]
 [  4.   5.   6.   7.]
 [  8.   9.  10.  11.]
 [ 12.  13.  14.  15.]
 [ 16.  17.  18.  19.]]
<NDArray 5x4 @cpu(0)> (5, 4)


In [15]:
print('A[2, 3] =', A[2, 3])

A[2, 3] = 
[ 11.]
<NDArray 1 @cpu(0)>


In [16]:
print('row 2', A[2, :])
print('column 3', A[:, 3])

row 2 
[  8.   9.  10.  11.]
<NDArray 4 @cpu(0)>
column 3 
[  3.   7.  11.  15.  19.]
<NDArray 5 @cpu(0)>


In [19]:
print('A =', A)
print('A Transpose =', A.T)

A = 
[[  0.   1.   2.   3.]
 [  4.   5.   6.   7.]
 [  8.   9.  10.  11.]
 [ 12.  13.  14.  15.]
 [ 16.  17.  18.  19.]]
<NDArray 5x4 @cpu(0)>
A Transpose = 
[[  0.   4.   8.  12.  16.]
 [  1.   5.   9.  13.  17.]
 [  2.   6.  10.  14.  18.]
 [  3.   7.  11.  15.  19.]]
<NDArray 4x5 @cpu(0)>


### 5. Tensors

In [20]:
X = nd.arange(24).reshape((2, 3, 4))
print('X.shape =', X.shape)
print('X =', X)

X.shape = (2, 3, 4)
X = 
[[[  0.   1.   2.   3.]
  [  4.   5.   6.   7.]
  [  8.   9.  10.  11.]]

 [[ 12.  13.  14.  15.]
  [ 16.  17.  18.  19.]
  [ 20.  21.  22.  23.]]]
<NDArray 2x3x4 @cpu(0)>


### 6. Element-wise operations

In [22]:
u = nd.array([1, 2, 4, 8])
print('u =', u)
v = nd.ones_like(u) * 2
print('v =', v)
print('u + v', u + v)
print('u - v', u - v)
print('u * v', u * v)
print('u / v', u / v)

u = 
[ 1.  2.  4.  8.]
<NDArray 4 @cpu(0)>
v = 
[ 2.  2.  2.  2.]
<NDArray 4 @cpu(0)>
u + v 
[  3.   4.   6.  10.]
<NDArray 4 @cpu(0)>
u - v 
[-1.  0.  2.  6.]
<NDArray 4 @cpu(0)>
u * v 
[  2.   4.   8.  16.]
<NDArray 4 @cpu(0)>
u / v 
[ 0.5  1.   2.   4. ]
<NDArray 4 @cpu(0)>


In [24]:
B = nd.ones_like(A) * 3
print('A =', A)
print('B =', B)
print('A + B =', A + B)
print('A * B =', A * B)

A = 
[[  0.   1.   2.   3.]
 [  4.   5.   6.   7.]
 [  8.   9.  10.  11.]
 [ 12.  13.  14.  15.]
 [ 16.  17.  18.  19.]]
<NDArray 5x4 @cpu(0)>
B = 
[[ 3.  3.  3.  3.]
 [ 3.  3.  3.  3.]
 [ 3.  3.  3.  3.]
 [ 3.  3.  3.  3.]
 [ 3.  3.  3.  3.]]
<NDArray 5x4 @cpu(0)>
A + B = 
[[  3.   4.   5.   6.]
 [  7.   8.   9.  10.]
 [ 11.  12.  13.  14.]
 [ 15.  16.  17.  18.]
 [ 19.  20.  21.  22.]]
<NDArray 5x4 @cpu(0)>
A * B = 
[[  0.   3.   6.   9.]
 [ 12.  15.  18.  21.]
 [ 24.  27.  30.  33.]
 [ 36.  39.  42.  45.]
 [ 48.  51.  54.  57.]]
<NDArray 5x4 @cpu(0)>


### 7. Basic properties of tensor arithmetic

In [27]:
a = 2
x = nd.ones(3)
y = nd.zeros(3)
print('a =', a)
print('x =', x)
print('y =', y)
print(x.shape)
print(y.shape)
print((a * x).shape)
print('a * x =', a*x)
print((a * x + y).shape)
print('a * x + y', a * x + y)

a = 2
x = 
[ 1.  1.  1.]
<NDArray 3 @cpu(0)>
y = 
[ 0.  0.  0.]
<NDArray 3 @cpu(0)>
(3,)
(3,)
(3,)
a * x = 
[ 2.  2.  2.]
<NDArray 3 @cpu(0)>
(3,)
a * x + y 
[ 2.  2.  2.]
<NDArray 3 @cpu(0)>


### 8. Sums and means

In [29]:
print('u =', u)
print(nd.sum(u))
print('A =', A)
print(nd.sum(A))

u = 
[ 1.  2.  4.  8.]
<NDArray 4 @cpu(0)>

[ 15.]
<NDArray 1 @cpu(0)>
A = 
[[  0.   1.   2.   3.]
 [  4.   5.   6.   7.]
 [  8.   9.  10.  11.]
 [ 12.  13.  14.  15.]
 [ 16.  17.  18.  19.]]
<NDArray 5x4 @cpu(0)>

[ 190.]
<NDArray 1 @cpu(0)>


In [30]:
print(nd.mean(A))
print(nd.sum(A) / A.size)


[ 9.5]
<NDArray 1 @cpu(0)>

[ 9.5]
<NDArray 1 @cpu(0)>


### 9. Dot products

In [34]:
print('u =', u)
print('v =', v)
print(nd.dot(u, v))
print('u * v =', u * v)
print(nd.sum(u * v))

u = 
[ 1.  2.  4.  8.]
<NDArray 4 @cpu(0)>
v = 
[ 2.  2.  2.  2.]
<NDArray 4 @cpu(0)>

[ 30.]
<NDArray 1 @cpu(0)>
u * v = 
[  2.   4.   8.  16.]
<NDArray 4 @cpu(0)>

[ 30.]
<NDArray 1 @cpu(0)>


### 10. Matrix - Vector Products

In [36]:
print('A =', A)
print('u =', u)
print('Au =', nd.dot(A, u))
print('A.shape', A.shape)
print('u.shape', u.shape)
print('Au.shape', nd.dot(A, u).shape)

A = 
[[  0.   1.   2.   3.]
 [  4.   5.   6.   7.]
 [  8.   9.  10.  11.]
 [ 12.  13.  14.  15.]
 [ 16.  17.  18.  19.]]
<NDArray 5x4 @cpu(0)>
u = 
[ 1.  2.  4.  8.]
<NDArray 4 @cpu(0)>
Au = 
[  34.   94.  154.  214.  274.]
<NDArray 5 @cpu(0)>
A.shape (5, 4)
u.shape (4,)
Au.shape (5,)


### 11. Matirx-Matrix multiplication

In [41]:
A = nd.arange(20).reshape((4, 5))
print('A =', A)
B = nd.arange(20).reshape((5, 4))
print('B =', B)
print('AB =', nd.dot(A, B))

A = 
[[  0.   1.   2.   3.   4.]
 [  5.   6.   7.   8.   9.]
 [ 10.  11.  12.  13.  14.]
 [ 15.  16.  17.  18.  19.]]
<NDArray 4x5 @cpu(0)>
B = 
[[  0.   1.   2.   3.]
 [  4.   5.   6.   7.]
 [  8.   9.  10.  11.]
 [ 12.  13.  14.  15.]
 [ 16.  17.  18.  19.]]
<NDArray 5x4 @cpu(0)>
AB = 
[[ 120.  130.  140.  150.]
 [ 320.  355.  390.  425.]
 [ 520.  580.  640.  700.]
 [ 720.  805.  890.  975.]]
<NDArray 4x4 @cpu(0)>


### 12. Norms

In [49]:
print('u =', u)
print('||u|| =', nd.norm(u))
print('||u|| =', nd.sqrt(nd.sum(u**2)))
print("u's  L1-norm =", nd.sum(nd.abs(u)))

u = 
[ 1.  2.  4.  8.]
<NDArray 4 @cpu(0)>
||u|| = 
[ 9.21954441]
<NDArray 1 @cpu(0)>
||u|| = 
[ 9.21954441]
<NDArray 1 @cpu(0)>
u's  L1-norm = 
[ 15.]
<NDArray 1 @cpu(0)>
