# MX

## 1. NDArray


In [1]:
import mxnet as mx
from mxnet import nd

### 1. 1. NDArray 생성하기

In [30]:
mx.random.seed(1)
x = nd.empty((3, 4)) # 튜플 형태로 넣어줘도 되며
print(x)
mx.random.seed(1)
y = nd.empty([3, 4]) # 리스트 형태로 넣어줘도 됨
print(y)
# 튜플로 넣으나 리스트로 넣으나 결과 값은 같음


[[  0.00000000e+00   3.68934881e+19  -2.29594762e+32   3.69024778e+19]
 [  3.94600243e+10   4.58490845e-41   0.00000000e+00   7.00649232e-45]
 [  7.56023296e+10   4.58490845e-41   0.00000000e+00   2.75513495e-40]]
<NDArray 3x4 @cpu(0)>

[[  0.00000000e+00   3.68934881e+19   0.00000000e+00   3.68934881e+19]
 [  3.94600243e+10   4.58490845e-41   0.00000000e+00   7.00649232e-45]
 [  7.56023296e+10   4.58490845e-41   0.00000000e+00   2.75513495e-40]]
<NDArray 3x4 @cpu(0)>


In [42]:
x = nd.zeros((3, 5))
print(x) # 모든 요소가 0으로 된 Array 생성
x = nd.ones((3, 4))
print(x) # 모든 요소가 1로 된 Array 생성
y = nd.random_normal(0, 1, shape=(3, 4))
print(y) # 평균이 0, sd가 1인 normal dist'n을 따르는 랜덤 넘버 생성


[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
<NDArray 3x5 @cpu(0)>

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
<NDArray 3x4 @cpu(0)>

[[ 2.39233518 -1.22338355  0.58518994  0.2414857 ]
 [ 1.08744419 -1.16463232 -0.15579289  0.277877  ]
 [ 1.32242072  1.69764137  0.24266219  0.39777336]]
<NDArray 3x4 @cpu(0)>


In [43]:
# shape, size
# 각 축의 길이는 shape으로 확인
# 각 축의 길이를 모두 곱하면 size
print(x.shape)
print(x.size)
print(x.shape[0], "*", x.shape[1], '=', x.size)

(3, 4)
12
3 * 4 = 12


### 1. 2. 연산

In [46]:
# 더하기 기호는 동일 위치 원소끼리 합
x + y

# shape이 다르면 덧셈 불가
z = nd.random_normal(0, 1, (3, 5))
print('x =', x)
print('z =', z)
print(x.shape, z.shape)
print(x + z) # 에러

x = 
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
<NDArray 3x4 @cpu(0)>
z = 
[[ 0.56612927 -1.14514875  0.19055244  1.25726521 -0.04120263]
 [-0.69165981  0.48786637 -0.85009855  0.42986658  1.8262856 ]
 [-0.44314346 -0.82162017  0.06977545  1.95015562 -0.50498772]]
<NDArray 3x5 @cpu(0)>
(3, 4) (3, 5)


MXNetError: [13:32:01] src/operator/tensor/./elemwise_binary_broadcast_op.h:67: Check failed: l == 1 || r == 1 operands could not be broadcast together with shapes [3,4] [3,5]

Stack trace returned 7 entries:
[bt] (0) 0   libmxnet.so                         0x0000000118dadb98 _ZN4dmlc15LogMessageFatalD2Ev + 40
[bt] (1) 1   libmxnet.so                         0x000000011905d4a8 _ZN5mxnet2op20BinaryBroadcastShapeERKN4nnvm9NodeAttrsEPNSt3__16vectorINS1_6TShapeENS5_9allocatorIS7_EEEESB_ + 3192
[bt] (2) 2   libmxnet.so                         0x0000000119d28c87 _ZN5mxnet10imperative12SetShapeTypeERKNS_7ContextERKN4nnvm9NodeAttrsERKNSt3__16vectorIPNS_7NDArrayENS8_9allocatorISB_EEEESG_PNS_12DispatchModeE + 1495
[bt] (3) 3   libmxnet.so                         0x0000000119d27889 _ZN5mxnet10Imperative6InvokeERKNS_7ContextERKN4nnvm9NodeAttrsERKNSt3__16vectorIPNS_7NDArrayENS8_9allocatorISB_EEEESG_ + 713
[bt] (4) 4   libmxnet.so                         0x0000000119ca8667 _Z22MXImperativeInvokeImplPviPS_PiPS0_iPPKcS5_ + 391
[bt] (5) 5   libmxnet.so                         0x0000000119ca9834 MXImperativeInvokeEx + 164
[bt] (6) 6   _ctypes.cpython-36m-darwin.so       0x000000010f64e2c7 ffi_call_unix64 + 79


In [47]:
# * 기호는 동일 위치 원소들의 곱
print(x * y)
# 역시 shape이 다르면 연산 불가
print(x * z)


[[ 2.39233518 -1.22338355  0.58518994  0.2414857 ]
 [ 1.08744419 -1.16463232 -0.15579289  0.277877  ]
 [ 1.32242072  1.69764137  0.24266219  0.39777336]]
<NDArray 3x4 @cpu(0)>


MXNetError: [13:39:08] src/operator/tensor/./elemwise_binary_broadcast_op.h:67: Check failed: l == 1 || r == 1 operands could not be broadcast together with shapes [3,4] [3,5]

Stack trace returned 7 entries:
[bt] (0) 0   libmxnet.so                         0x0000000118dadb98 _ZN4dmlc15LogMessageFatalD2Ev + 40
[bt] (1) 1   libmxnet.so                         0x000000011905d4a8 _ZN5mxnet2op20BinaryBroadcastShapeERKN4nnvm9NodeAttrsEPNSt3__16vectorINS1_6TShapeENS5_9allocatorIS7_EEEESB_ + 3192
[bt] (2) 2   libmxnet.so                         0x0000000119d28c87 _ZN5mxnet10imperative12SetShapeTypeERKNS_7ContextERKN4nnvm9NodeAttrsERKNSt3__16vectorIPNS_7NDArrayENS8_9allocatorISB_EEEESG_PNS_12DispatchModeE + 1495
[bt] (3) 3   libmxnet.so                         0x0000000119d27889 _ZN5mxnet10Imperative6InvokeERKNS_7ContextERKN4nnvm9NodeAttrsERKNSt3__16vectorIPNS_7NDArrayENS8_9allocatorISB_EEEESG_ + 713
[bt] (4) 4   libmxnet.so                         0x0000000119ca8667 _Z22MXImperativeInvokeImplPviPS_PiPS0_iPPKcS5_ + 391
[bt] (5) 5   libmxnet.so                         0x0000000119ca9834 MXImperativeInvokeEx + 164
[bt] (6) 6   _ctypes.cpython-36m-darwin.so       0x000000010f64e2c7 ffi_call_unix64 + 79


In [53]:
# exponential 취하고 싶을 때
print(nd.exp(y))
print(y)
print(nd.log(nd.exp(y)))


[[ 10.93900871   0.29423293   1.79533195   1.27313924]
 [  2.9666822    0.31203738   0.85573637   1.32032382]
 [  3.7524941    5.46105146   1.27463794   1.48850667]]
<NDArray 3x4 @cpu(0)>

[[ 2.39233518 -1.22338355  0.58518994  0.2414857 ]
 [ 1.08744419 -1.16463232 -0.15579289  0.277877  ]
 [ 1.32242072  1.69764137  0.24266219  0.39777336]]
<NDArray 3x4 @cpu(0)>

[[ 2.39233518 -1.22338355  0.58518994  0.24148569]
 [ 1.08744419 -1.16463232 -0.15579292  0.27787703]
 [ 1.32242072  1.69764137  0.24266216  0.39777339]]
<NDArray 3x4 @cpu(0)>


In [60]:
# 행렬의 곱처럼 내적 연산(dot product)
print(x.shape)
print(y.shape)
# 행렬 곱이 불가능한 형태이므로 X 혹은 Y 에 Transpose 필요
y_t = y.T
print(x.shape)
print(y_t.shape)
print(nd.dot(x, y_t))
print(nd.dot(x, y_t).shape)



(3, 4)
(3, 4)
(3, 4)
(4, 3)

[[ 1.99562728  0.04489598  3.66049767]
 [ 1.99562728  0.04489598  3.66049767]
 [ 1.99562728  0.04489598  3.66049743]]
<NDArray 3x3 @cpu(0)>
(3, 3)


### 1. 3. 효율적인 메모리 사용

In [61]:
# In-Place 연산
print('id(y):', id(y))
y = y + x
print('id(y):', id(y))
# 4764587120라는 곳에 y를 assing하고 있다가 y를 y+x로 대체하였는데 y의 할당 공간이 4764656416으로 바뀜
# y = y+x를 했을 때 y의 저장 위치가 바뀌지 않는다면 효율적인 연산이 가능

id(y): 4764587120
id(y): 4764656416


In [64]:
# [:]연산자를 사용하면 원래 있던 자리에 그대로 할당 가능
print('id(y):', id(y))
print(y)
y[:] = x + y
print('id(y):', id(y))
print(y)

id(y): 4764656416

[[ 5.39233494  1.77661645  3.58518982  3.2414856 ]
 [ 4.08744431  1.83536768  2.84420705  3.27787685]
 [ 4.3224206   4.69764137  3.24266219  3.39777327]]
<NDArray 3x4 @cpu(0)>
id(y): 4764656416

[[ 6.39233494  2.77661657  4.58518982  4.2414856 ]
 [ 5.08744431  2.83536768  3.84420705  4.27787685]
 [ 5.3224206   5.69764137  4.24266243  4.39777327]]
<NDArray 3x4 @cpu(0)>


In [67]:
# 그런데 [:]조차도 조금의 buffer는 존재함
# 이를 해결하기 위해 elemwise_add를 이용
print(y)
print('id(y):', id(y))
print(nd.elemwise_add(x, y, out=y))
print('id(y):', id(y))
print(y)
print('id(y):', id(y))
# id가 변하지 않고 연산은 수행됨


[[ 8.39233494  4.77661657  6.58518982  6.2414856 ]
 [ 7.08744431  4.83536768  5.84420681  6.27787685]
 [ 7.3224206   7.69764137  6.24266243  6.39777327]]
<NDArray 3x4 @cpu(0)>
id(y): 4764656416

[[ 9.39233494  5.77661657  7.58518982  7.2414856 ]
 [ 8.08744431  5.83536768  6.84420681  7.27787685]
 [ 8.32242012  8.69764137  7.24266243  7.39777327]]
<NDArray 3x4 @cpu(0)>
id(y): 4764656416

[[ 9.39233494  5.77661657  7.58518982  7.2414856 ]
 [ 8.08744431  5.83536768  6.84420681  7.27787685]
 [ 8.32242012  8.69764137  7.24266243  7.39777327]]
<NDArray 3x4 @cpu(0)>
id(y): 4764656416


In [71]:
# 이와 유사하게 += 기호 사용 가능
print(x)
print('id(x):', id(x))
x += y
print(x)
print('id(x):', id(x))
# x의 자리에 x+y의 값을 할당하는데 id는 변하지 않고 그대로 유지


[[ 19.78466988  12.55323315  16.17037964  15.48297119]
 [ 17.17488861  12.67073536  14.68841362  15.55575371]
 [ 17.64484024  18.39528275  15.48532486  15.79554749]]
<NDArray 3x4 @cpu(0)>
id(x): 4764587680

[[ 29.17700577  18.32984924  23.75556946  22.72445679]
 [ 25.26233292  18.50610352  21.53261948  22.83362961]
 [ 25.96726036  27.09292412  22.72798729  23.19332123]]
<NDArray 3x4 @cpu(0)>
id(x): 4764587680


### 1. 4. 슬라이싱 및 인덱싱

In [75]:
# slicing은 []를 사용
print(x)
print(x[0:2]) # matrix의 행처럼 Slicing
print(x[1,1]) # axis-0의 1번째 index, axis-1의 1번째 index값을 가져옴
print(x[1:3, 0:2]) # R과 유사하게 multi-dimensional Slicing 가능


[[ 29.17700577  18.32984924  23.75556946  22.72445679]
 [ 25.26233292  18.50610352  21.53261948  22.83362961]
 [ 25.96726036  27.09292412  22.72798729  23.19332123]]
<NDArray 3x4 @cpu(0)>

[[ 29.17700577  18.32984924  23.75556946  22.72445679]
 [ 25.26233292  18.50610352  21.53261948  22.83362961]]
<NDArray 2x4 @cpu(0)>

[ 18.50610352]
<NDArray 1 @cpu(0)>

[[ 25.26233292  18.50610352]
 [ 25.96726036  27.09292412]]
<NDArray 2x2 @cpu(0)>


In [82]:
z = nd.random_normal(10, 4, (3, 5, 4))
print(z) 
print(z[0:2]) # axis-0을 기준으로 0, 1 index에 해당하는 array를 slicing
print(z[0:2, 1:4]) # axis-0을 기준으로 0, 1 axis-1을 기준으로 1, 2, 3에 해당하는 array를 slicing
print(z[:, 1:4]) # axis-1을 기준으로 1, 2, 3에 해당하는 array를 slicing
print(z[0:1, 1:4, :2]) # axis-0을 기준으로 0 axis-1을 기준으로 1, 2, 3 axis-2를 기준으로 0, 1에 해당하는
                       # array를 slicing


[[[  6.12348366   8.82448959   8.43239403   4.2309432 ]
  [ 21.53680229   3.25406027  15.06999969  10.21038246]
  [ 10.69213009   9.82289982   6.98856163   7.81310558]
  [  7.44261837  11.4095993   10.01848602  10.94968987]
  [  8.25931931  17.34367943   9.93625832  19.36527061]]

 [[  3.32978058   9.40115738  12.63013744   9.87531853]
  [  2.23682976  16.61660957  17.72768021  15.54632664]
  [ 14.86494732   5.22474384  19.15210533  15.91779232]
  [ 10.77911186  17.54016113   5.10908937  10.19560909]
  [  6.2431221    4.58770132   4.38505173  15.12139511]]

 [[  9.81549835   7.47438717  12.53130436  11.92798328]
  [  7.26695538  13.69740486  14.15141487  12.40248394]
  [  9.40353298   1.05739594   8.09939861  17.74224663]
  [ 13.93233204  15.96765709  13.80722332  11.0529232 ]
  [ 13.36735439  18.27962875  13.59220123   9.18781185]]]
<NDArray 3x5x4 @cpu(0)>

[[[  6.12348366   8.82448959   8.43239403   4.2309432 ]
  [ 21.53680229   3.25406027  15.06999969  10.21038246]
  [ 10.69213009 

### 1. 5. Broadcasting

In [88]:
X = nd.ones((3,3))
print('X =', X)
y = nd.arange(3)
print('y =', y)
print('X + y =', X + y)
# 1차원의 vector(y)를 복사해서 2차원 NDArray(X)에 순서(가로)대로 더해줌
y_2dim = y.reshape((1, 3))
print(y_2dim)
print('X + y_2dim =', X + y_2dim)
# y를 2차원의 NDArray 형태로 바꿔줘도 결과는 동일

X = 
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
<NDArray 3x3 @cpu(0)>
y = 
[ 0.  1.  2.]
<NDArray 3 @cpu(0)>
X + y = 
[[ 1.  2.  3.]
 [ 1.  2.  3.]
 [ 1.  2.  3.]]
<NDArray 3x3 @cpu(0)>

[[ 0.  1.  2.]]
<NDArray 1x3 @cpu(0)>
X + y_2dim = 
[[ 1.  2.  3.]
 [ 1.  2.  3.]
 [ 1.  2.  3.]]
<NDArray 3x3 @cpu(0)>


In [86]:
# 세로로 더하고 싶다면 y의 shape을 바꾸면 된다.
y_transpose = y.reshape((3,1))
print('y_transpose =', y_transpose)
print('X + y_transpose =', X + y_transpose)

y_transpose = 
[[ 0.]
 [ 1.]
 [ 2.]]
<NDArray 3x1 @cpu(0)>
X + y_transpose = 
[[ 1.  1.  1.]
 [ 2.  2.  2.]
 [ 3.  3.  3.]]
<NDArray 3x3 @cpu(0)>


In [90]:
z = nd.arange(2)
print(z)
print('X + z =', X + z)
# 더하려는 Vector의 길이가 NDArray의 해당 축의 길이와 맞지 않으면 더할 수 없다.


[ 0.  1.]
<NDArray 2 @cpu(0)>


MXNetError: [11:36:37] src/operator/tensor/./elemwise_binary_broadcast_op.h:67: Check failed: l == 1 || r == 1 operands could not be broadcast together with shapes [3,3] [2]

Stack trace returned 7 entries:
[bt] (0) 0   libmxnet.so                         0x0000000118dadb98 _ZN4dmlc15LogMessageFatalD2Ev + 40
[bt] (1) 1   libmxnet.so                         0x000000011905d4a8 _ZN5mxnet2op20BinaryBroadcastShapeERKN4nnvm9NodeAttrsEPNSt3__16vectorINS1_6TShapeENS5_9allocatorIS7_EEEESB_ + 3192
[bt] (2) 2   libmxnet.so                         0x0000000119d28c87 _ZN5mxnet10imperative12SetShapeTypeERKNS_7ContextERKN4nnvm9NodeAttrsERKNSt3__16vectorIPNS_7NDArrayENS8_9allocatorISB_EEEESG_PNS_12DispatchModeE + 1495
[bt] (3) 3   libmxnet.so                         0x0000000119d27889 _ZN5mxnet10Imperative6InvokeERKNS_7ContextERKN4nnvm9NodeAttrsERKNSt3__16vectorIPNS_7NDArrayENS8_9allocatorISB_EEEESG_ + 713
[bt] (4) 4   libmxnet.so                         0x0000000119ca8667 _Z22MXImperativeInvokeImplPviPS_PiPS0_iPPKcS5_ + 391
[bt] (5) 5   libmxnet.so                         0x0000000119ca9834 MXImperativeInvokeEx + 164
[bt] (6) 6   _ctypes.cpython-36m-darwin.so       0x000000010f64e2c7 ffi_call_unix64 + 79


### 1. 6. MXNet NDArray에서 NumPy ndarray로 변경

In [103]:
print('class of y is', type(y))
print('y =', y)

class of y is <class 'mxnet.ndarray.ndarray.NDArray'>
y = 
[ 0.  1.  2.]
<NDArray 3 @cpu(0)>


In [104]:
y_np = y.asnumpy()
print('class of y_np is', type(y_np))
print('y_np =', y_np)

class of y_np is <class 'numpy.ndarray'>
y_np = [ 0.  1.  2.]


### 1. 7. 연산 수행 환경 설정


In [ ]:
# gpu 환경 설정 실패로 불가능

In [105]:
z = nd.ones((3,3), ctx=mx.gpu(0))

MXNetError: [13:15:47] src/imperative/imperative.cc:78: Operator _ones is not implemented for GPU.

Stack trace returned 6 entries:
[bt] (0) 0   libmxnet.so                         0x0000000118dadb98 _ZN4dmlc15LogMessageFatalD2Ev + 40
[bt] (1) 1   libmxnet.so                         0x0000000119d23cd4 _ZN5mxnet10Imperative8InvokeOpERKNS_7ContextERKN4nnvm9NodeAttrsERKNSt3__16vectorIPNS_7NDArrayENS8_9allocatorISB_EEEESG_RKNS9_INS_9OpReqTypeENSC_ISH_EEEENS_12DispatchModeENS_10OpStatePtrE + 1972
[bt] (2) 2   libmxnet.so                         0x0000000119d278da _ZN5mxnet10Imperative6InvokeERKNS_7ContextERKN4nnvm9NodeAttrsERKNSt3__16vectorIPNS_7NDArrayENS8_9allocatorISB_EEEESG_ + 794
[bt] (3) 3   libmxnet.so                         0x0000000119ca8667 _Z22MXImperativeInvokeImplPviPS_PiPS0_iPPKcS5_ + 391
[bt] (4) 4   libmxnet.so                         0x0000000119ca9834 MXImperativeInvokeEx + 164
[bt] (5) 5   _ctypes.cpython-36m-darwin.so       0x000000010f64e2c7 ffi_call_unix64 + 79
